project_postgres_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: 'Enter your default PostgreSQL password here'
      port: 5432
      dbname: postgres
      schema: project2
      threads: 1
