version: 2

sources:
  - name: project2
    database: postgres
    schema: project2
    tables:
      - name: customer_dimension
      - name: product_dimension
      - name: time_dimension
      - name: sales_fact
